Repository edgargavioli/pi5-app-estudo, pull requests merged in 2025-05, with the labels that each got.

#34 feat: adiciona tela para adicionar nova materia para a prova
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/components/card_widget.dart
  pi5_ms_mobile/lib/src/presentation/CronogramaPage.dart
  pi5_ms_mobile/lib/src/presentation/DesempenhoPage.dart
  pi5_ms_mobile/lib/src/presentation/LoginPage.dart
  pi5_ms_mobile/lib/src/presentation/materias/AdicionarMateriaPage.dart
  pi5_ms_mobile/lib/src/presentation/materias/MateriasListagemPage.dart
Labels: feature, frontend, chore

#35 Feature/11
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/presentation/provas/EditProvaPage.dart
Labels: feature, frontend

#36 feat: adiciona tela de estudos
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/components/scaffold_widget.dart
  pi5_ms_mobile/lib/src/presentation/estudos/EstudosPage.dart
Labels: feature, frontend

#37 feat:adiciona tela de criar provas
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/presentation/provas/AdicionarProvaPage.dart
  pi5_ms_mobile/lib/src/presentation/provas/ProvasListagemPage.dart
Labels: feature, frontend

#38 feat: adiciona a tela de histórico
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/components/scaffold_widget.dart
  pi5_ms_mobile/lib/src/presentation/CronogramaPage.dart
  pi5_ms_mobile/lib/src/presentation/historico/HistoricoPage.dart
Labels: feature, frontend

#42 feature:adiciona telas de perfil, edição de perfil e alteração de senha
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/components/navigation_widget.dart
  pi5_ms_mobile/lib/src/components/scaffold_widget.dart
  pi5_ms_mobile/lib/src/presentation/provas/AdicionarProvaPage.dart
  pi5_ms_mobile/lib/src/presentation/user/UserProfilePageInfo.dart
  pi5_ms_mobile/lib/src/presentation/user/UserProfilePageMain.dart
Labels: feature, frontend

#44 feat: adiciona e corrige problemas no sistema e na navegação
  pi5_ms_mobile/lib/main.dart
  pi5_ms_mobile/lib/src/components/appbar_widget.dart
  pi5_ms_mobile/lib/src/components/navigation_widget.dart
  pi5_ms_mobile/lib/src/components/pageview/page_view.dart
  pi5_ms_mobile/lib/src/components/scaffold_widget.dart
  pi5_ms_mobile/lib/src/presentation/CronogramaPage.dart
  pi5_ms_mobile/lib/src/presentation/HomePage.dart
  pi5_ms_mobile/lib/src/presentation/ProvasPage.dart
  pi5_ms_mobile/lib/src/presentation/auth/login_page.dart
  pi5_ms_mobile/lib/src/presentation/auth/nova_senha_page.dart
  pi5_ms_mobile/lib/src/presentation/auth/recuperar_senha_page.dart
  pi5_ms_mobile/lib/src/presentation/auth/registro_page.dart
  pi5_ms_mobile/lib/src/presentation/auth/verificar_codigo_page.dart
  pi5_ms_mobile/lib/src/presentation/cronograma/cronograma_page.dart
  pi5_ms_mobile/lib/src/presentation/desempenho/desempenho_page.dart
  pi5_ms_mobile/lib/src/presentation/estudos/estudos_page.dart
  pi5_ms_mobile/lib/src/presentation/historico/historico_page.dart
  pi5_ms_mobile/lib/src/presentation/inicio_page.dart
  pi5_ms_mobile/lib/src/presentation/materias/MateriasListagemPage.dart
  pi5_ms_mobile/lib/src/presentation/materias/adicionar_materia_page.dart
  pi5_ms_mobile/lib/src/presentation/materias/materias_config_page.dart
  pi5_ms_mobile/lib/src/presentation/materias/materias_listagem_page.dart
  pi5_ms_mobile/lib/src/presentation/provas/adicionar_prova_page.dart
  pi5_ms_mobile/lib/src/presentation/provas/editar_prova_page.dart
  pi5_ms_mobile/lib/src/presentation/provas/provas_listagem_page.dart
  pi5_ms_mobile/lib/src/presentation/user/UserProfilePageInfo.dart
  pi5_ms_mobile/lib/src/presentation/user/UserProfilePageMain.dart
  pi5_ms_mobile/lib/src/presentation/user/perfil_usuario_page.dart
  pi5_ms_mobile/lib/src/presentation/user/perfil_usuario_page_info.dart
  pi5_ms_mobile/pubspec.lock
  pi5_ms_mobile/pubspec.yaml
Labels: bug, feature, frontend, chore

#46 chore: adiciona o template dos microsservicos
  pi5_ms_template/.env.example
  pi5_ms_template/main.js
  pi5_ms_template/package-lock.json
  pi5_ms_template/package.json
  pi5_ms_template/src/app.js
  pi5_ms_template/src/application/explication.txt
  pi5_ms_template/src/config/swagger.json
  pi5_ms_template/src/domain/explication.txt
  pi5_ms_template/src/infrastructure/explication.txt
  pi5_ms_template/src/infrastructure/persistence/prisma/prismaClient.js
  pi5_ms_template/src/infrastructure/persistence/prisma/schema.prisma
  pi5_ms_template/src/presentation/explication.txt
  pi5_ms_template/src/presentation/middlewares/handler.js
  pi5_ms_template/src/presentation/middlewares/hateoas.js
  pi5_ms_template/src/presentation/middlewares/order.js
  pi5_ms_template/src/presentation/middlewares/validator.js
  pi5_ms_template/src/presentation/middlewares/whitelist.js
  pi5_ms_template/src/presentation/routes/helper/404.js
  pi5_ms_template/src/presentation/routes/helper/500.js
  pi5_ms_template/src/presentation/routes/routes.js
  pi5_ms_template/src/server.js
  pi5_ms_template/src/swagger.js
Labels: feature, frontend, chore
